CC = g++ # Flag for implicit rules
# this is heuristically generated, and may not be 

hello:
	echo "Test"

jsono:
	$(CC) -I include -c ".\src\lib_json\*.cpp"

changer:
	$(CC) light_changer.cc -o light_changer -I \include
