# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
      env:
            REACT_APP_LIFX: ${{ app_env.REACT_APP_LIFX }}
            REACT_APP_PSN_TOKEN: ${{ app_env.REACT_APP_PSN_TOKEN }}
            REACT_APP_LIGHT_ID: ${{ app_env.REACT_APP_LIGHT_ID }}
            REACT_APP_BACKEND_PORT: ${{ app_env.REACT_APP_BACKEND_PORT }}
    - run: npm i jest
      working-directory: ./psn-lightchanger
    - run: nohup node server.js &
      working-directory: ./psn-lightchanger
    - run: npm run test
      working-directory: ./psn-lightchanger